export declare function unique<T>(items: T[]): T[];
export declare function chunk<T>(items: T[], size: number): T[][];
export declare function groupBy<T, K extends PropertyKey>(items: T[], keyFn: (item: T) => K): Record<K, T[]>;
export declare function flatten<T>(items: T[][]): T[];
export declare function compact<T>(items: Array<T | null | undefined>): T[];
export declare function first<T>(items: T[]): T | null;
export declare function last<T>(items: T[]): T | null;
export declare function sortBy<T>(items: T[], keyFn: (item: T) => string | number): T[];
export declare function keyBy<T, K extends PropertyKey>(items: T[], keyFn: (item: T) => K): Record<K, T>;
export declare function filter<T>(items: T[], predicate: (item: T) => boolean): T[];
export declare function find<T>(items: T[], predicate: (item: T) => boolean): T | null;
