export declare const DEFAULT_PATTERN = "iso8601";
export declare function now(): Date;
export declare function formatDatetime(value: Date, pattern?: string): string;
export declare function parseDatetime(value: string, pattern?: string): Date | null;
export declare function addDays(value: Date, days: number): Date;
export declare function addHours(value: Date, hours: number): Date;
export declare function addMinutes(value: Date, minutes: number): Date;
export declare function diffMillis(earlier: Date, later: Date): number;
export declare function isBefore(first: Date, second: Date): boolean;
export declare function isAfter(first: Date, second: Date): boolean;
export declare function startOfDayUtc(value: Date): Date;
export declare function endOfDayUtc(value: Date): Date;
export declare function toUnixMillis(value: Date): number;
export declare function fromUnixMillis(value: number): Date | null;
export declare function isSameInstant(first: Date, second: Date): boolean;
