export type JsonObject = Record<string, unknown>;
export declare function pick(source: JsonObject, keys: string[]): JsonObject;
export declare function omit(source: JsonObject, keys: string[]): JsonObject;
export declare function getPath(source: unknown, path: string): unknown;
export declare function setPath(source: JsonObject, path: string, value: unknown): JsonObject;
export declare function hasPath(source: unknown, path: string): boolean;
export declare function shallowMerge(base: unknown, overlay: unknown): unknown;
export declare function deepMerge(base: unknown, overlay: unknown): unknown;
export declare function compactObject(source: JsonObject): JsonObject;
export declare function keys(source: JsonObject): string[];
export declare function values(source: JsonObject): unknown[];
