export declare function isBlank(value: string | null | undefined): boolean;
export declare function trim(value: string): string;
export declare function truncate(value: string, maxLen: number, suffix?: string): string;
export declare function capitalize(value: string): string;
export declare function camelCase(value: string): string;
export declare function snakeCase(value: string): string;
export declare function kebabCase(value: string): string;
export declare function slugify(value: string): string;
export declare function mask(value: string, visibleStart: number, visibleEnd: number, maskChar?: string): string;
export declare function padStart(value: string, targetLen: number, padChar?: string): string;
export declare function padEnd(value: string, targetLen: number, padChar?: string): string;
export declare function startsWith(value: string, prefix: string): boolean;
export declare function endsWith(value: string, suffix: string): boolean;
export declare function contains(value: string, substring: string): boolean;
export declare function replaceAll(value: string, search: string, replacement: string): string;
export declare function split(value: string, delimiter: string, trimParts?: boolean): string[];
export declare function join(parts: string[], separator: string): string;
export declare function repeat(value: string, count: number): string;
export declare function normalizeWhitespace(value: string): string;
export declare function template(pattern: string, values: Record<string, string>): string;
